# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160901_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=1, upload_to=b'', verbose_name='media/'),
            preserve_default=False,
        ),
    ]
