# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_user',
            field=models.EmailField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
