# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_email_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_user',
        ),
    ]
