# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyresult', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportfield',
            old_name='callss',
            new_name='calls',
        ),
        migrations.RenameField(
            model_name='reportfield',
            old_name='contract',
            new_name='contracts',
        ),
    ]
